# kb-local server-side provisioning (ADMIN ONLY - run on the admin's machine).
# Reads a "kb-provision-request.txt" generated by the contributor's setup script
# and completes all server-side ops in one shot:
#   1. verify the server account exists on 192.168.0.10 (create NOT supported - ask ops)
#   2. add the account to group `rag` (sudo)
#   3. append the contributor's public key to the account's authorized_keys (sudo)
#   4. register a central-instance watch for /data/RAG/bak/<author> (author from request)
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\provision_server.ps1 -RequestFile <path-to-request>
# Requires: admin's ssh key (~/.ssh/id_rsa_2048) with sudo rights on 192.168.0.10.
# NOTE: keep this file ASCII-only (PS 5.1 parses BOM-less files as ANSI).

param(
    [Parameter(Mandatory = $true)][string]$RequestFile,
    [string]$Server = "192.168.0.10",
    [string]$AdminUser = "caopingtao"
)
$ErrorActionPreference = "Stop"

if (-not (Test-Path $RequestFile)) { Write-Host "request file not found: $RequestFile"; exit 1 }
$req = @{}
Get-Content $RequestFile | ForEach-Object {
    $i = $_.IndexOf("=")
    if ($i -gt 0) { $req[$_.Substring(0, $i)] = $_.Substring($i + 1) }
}
$author  = $req["author"]
$sshUser = $req["ssh_user"]
$pubkey  = $req["pubkey"]
if (-not $author -or -not $sshUser -or -not $pubkey) {
    Write-Host "request file incomplete (need author= ssh_user= pubkey=): $RequestFile"; exit 1
}
Write-Host "provisioning: author=$author ssh_user=$sshUser server=$Server"

$sshArgs = @("-i", "$env:USERPROFILE\.ssh\id_rsa_2048", "-o", "BatchMode=yes",
             "-o", "StrictHostKeyChecking=accept-new", "$AdminUser@$Server")

# 1. account exists?
$exists = & ssh @sshArgs "id -u $sshUser 2>/dev/null | wc -l"
if ("$exists".Trim() -eq "0") {
    Write-Host "[FAIL] server account '$sshUser' does not exist on $Server."
    Write-Host "       ask ops to create it first, then rerun this script."; exit 1
}
Write-Host "[1/3] account exists"

# 2. add to rag group
& ssh @sshArgs "sudo usermod -aG rag $sshUser"
if ($LASTEXITCODE -ne 0) { Write-Host "[FAIL] usermod"; exit 1 }
Write-Host "[2/3] added to group rag"

# 3. inject pubkey (idempotent: skip if already present)
$pubEsc = $pubkey -replace "'","'\''"
& ssh @sshArgs ("sudo mkdir -p /home/$sshUser/.ssh && " +
    "sudo grep -qF '$pubEsc' /home/$sshUser/.ssh/authorized_keys 2>/dev/null || " +
    "echo '$pubEsc' | sudo tee -a /home/$sshUser/.ssh/authorized_keys >/dev/null; " +
    "sudo chown -R ${sshUser}:${sshUser} /home/$sshUser/.ssh && " +
    "sudo chmod 700 /home/$sshUser/.ssh && sudo chmod 600 /home/$sshUser/.ssh/authorized_keys")
if ($LASTEXITCODE -ne 0) { Write-Host "[FAIL] pubkey injection"; exit 1 }
Write-Host "[3/3] pubkey injected (idempotent)"

# 4. central watch for this author (unified layout: /data/RAG/bak/<author>/<project>/docs/)
& ssh @sshArgs ("export PATH=`$HOME/.local/bin:`$PATH && cd ~/rag-kb && export HF_HUB_OFFLINE=1 && " +
    "uv run kb watch add /data/RAG/bak/$author --project glow --strategy first_subdir " +
    "--include '*/docs/*' --exclude '**/node_modules/**' --exclude '**/vendor/**' --author $author")
if ($LASTEXITCODE -ne 0) { Write-Host "[FAIL] central watch add"; exit 1 }

# 5. restart central service so the new watch dir is monitored in real time
& ssh @sshArgs "sudo systemctl restart kb-central-mcp"
if ($LASTEXITCODE -ne 0) { Write-Host "[FAIL] service restart"; exit 1 }

Write-Host ""
Write-Host "== provisioned =="
Write-Host "reply to the contributor: backup is ready (they should run"
Write-Host "backup.py --dry-run once to verify ssh access)."
